// src/components/game-results/index.tsx
import * as React from 'react';
import * as PropTypes from 'prop-types';

import * as types from '../../constants';

interface Result {
  username: string;
  place: number,

  cards: number[],
  chips: number,
  points: number,

  dicesCount: number,
}

export const GameResults = ({ game, players, playersInGame }: { game: string, players: types.Player[], playersInGame: types.PlayerInGame[] }) => {

  console.log(game, playersInGame);

  const results: Result[] = playersInGame.map((playerInGame, index) => {
    return {
      username: players[index].username,
      cards: playerInGame.cards || [],
      chips: playerInGame.chips || 0,
      points: playerInGame.points || 0,
      place: playerInGame.place,
      dicesCount: playerInGame.dicesCount || 0,
    };
  });

  results.sort((a, b) => {
    if (a.place === b.place) {
      return a.points - b.points;
    }
    return a.place - b.place;
  });

  return (
    <div>
      {results.map((result, index) => (
        <div key={index}>
          {result.place} place - {result.username}
          {game === types.NO_THANKS && <span>({result.points} points)</span>}
          {game === types.PERUDO && result.dicesCount ? <span>(dices remaining: {result.dicesCount})</span> : ''}
        </div>
      ))}
    </div>
  );
}

GameResults.propTypes = {
  game: PropTypes.string.isRequired,
  players: PropTypes.array.isRequired,
  playersInGame: PropTypes.array.isRequired,
}

// src/app/game-results/game-results.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

import { GamesserverService } from './../gamesserver.service';

@Component({
  selector: 'app-game-results',
  templateUrl: './game-results.component.html',
  styleUrls: ['./game-results.component.css']
})
export class GameResultsComponent implements OnInit, OnDestroy {
  gameSubscription: any;
  results: any;

  constructor(
    public gamesServer: GamesserverService,
  ) {
    this.gameSubscription = gamesServer.getGame().subscribe((openGame) => {
      if (openGame && openGame.gameInfo.players) {
        this.results = openGame.gameInfo.players;
        this.results.forEach((result, i) => {
          result.username = openGame.players[i].username;
        });
        this.results.sort((a, b) => {
          if (a.place === b.place) {
            return a.points > b.points;
          }
          return a.place > b.place;
        });
        console.log(this.results);
      }
    });
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    this.gameSubscription.unsubscribe();
  }
}

<ul>
  Game results:
  <br>
  <br>
  <li *ngFor="let result of results">
    <span class="result">{{ result.place }}</span> place
    <br>
    <span class="result">{{ result.username }}</span>
    <span *ngIf="result.points">
      <br>
      <span class="result">{{ result.points }}</span> points</span>
    <span *ngIf="result.cards">
      <br>
      <span *ngFor="let card of result.cards; let i = index">
        <span class="{{ i === 0 || card !== result.cards[i - 1] + 1 ? 'nothanks-bold' : 'nothanks-grey' }}"> {{ card }}</span>
      </span>
    </span>
    <span *ngIf="result.chips || result.chips === 0">
      <br>
      <span class="chips">{{ CHIP.repeat(result.chips) }}</span> ({{ result.chips }})</span>

    <span *ngIf="result.dicesCount"> | dices remaining: {{ result.dicesCount }}</span>
    <br>
    <br>
  </li>
</ul>
