// src/containers/perudo/index.tsx
import * as React from 'react';

import { DICES } from '../../services';
import * as types from '../../constants';

interface PerudoProps extends React.Props<{}> {
	game: types.Game,
	currentUsername: string | null,
	move: any,
}

export class Perudo extends React.Component<PerudoProps, {}> {

	diceNumber: number;
	diceFigure: number;

	allDicesCount: number;

	currentBet: String = '';
	myBet: String = '';

	myBetNumberIncDisable: Boolean;
	myBetNumberDecDisable: Boolean;
	myBetFigureIncDisable: Boolean;
	myBetFigureDecDisable: Boolean;

	diceNumberInc() {
		if (!this.myBetNumberIncDisable) {
			this.diceNumber++;
			this.updateMyBet();
		}
	}

	diceNumberDec() {
		if (!this.myBetNumberDecDisable) {
			this.diceNumber--;
			this.updateMyBet();
		}
	}

	diceFigureInc() {
		if (!this.myBetFigureIncDisable) {
			this.diceFigure++;
			this.updateMyBet();
		}
	}

	diceFigureDec() {
		if (!this.myBetFigureDecDisable) {
			this.diceFigure--;
			this.updateMyBet();
		}
	}

	moveBet() {
		this.props.move({ number: this.diceNumber, figure: this.diceFigure });
		this.diceNumber = 0;
		this.diceFigure = 0;
	}

	moveNotBelieve() {
		this.props.move({ notBelieve: true });
		this.diceNumber = 0;
		this.diceFigure = 0;
	}

	updateAllDicesCount() {
		const {
			game: {
				gameInfo: {
					players = [],
				},
			},
		} = this.props;

		this.allDicesCount = 0;

		players.forEach(player => {
			this.allDicesCount += player.dicesCount || 0;
		});
	}

	updateMyBet() {
		const {
			game: {
				nextPlayersNames = [],
				gameInfo: {
					currentDiceNumber = 0,
					currentDiceFigure = 0,
				},
			},
			currentUsername,
		} = this.props;

		if (nextPlayersNames[0] === currentUsername) {
			if (!this.diceNumber || !this.diceFigure) {
				this.diceNumber = 1;
				this.diceFigure = 2;
				if (currentDiceNumber && currentDiceFigure) {
					this.diceNumber = currentDiceNumber + 1;
					this.diceFigure = currentDiceFigure;
				}
			}
		}

		this.myBet = '';
		for (let i = 0; i < this.diceNumber; i++) {
			this.myBet = `${this.myBet}${DICES[this.diceFigure - 1]}`;
		}

		this.myBetNumberIncDisable = this.diceNumber >= this.allDicesCount;
		this.myBetNumberDecDisable = this.diceNumber <= 1
			|| this.diceNumber <= currentDiceNumber
			|| (this.diceNumber <= currentDiceNumber + 1 && this.diceFigure <= currentDiceFigure);

		this.myBetFigureIncDisable = this.diceFigure >= 6;
		this.myBetFigureDecDisable = this.diceFigure <= 2
			|| (this.diceNumber === currentDiceNumber && this.diceFigure <= currentDiceFigure + 1);
	}

	render() {
		this.updateAllDicesCount();
		this.updateMyBet();

		const { game, currentUsername } = this.props;

		return (
			<div>
				<div>
					{game.name}
				</div>
				<div>
					{game.nextPlayersNames && game.nextPlayersNames[0] === currentUsername && <span>YOUR MOVE!</span>}
				</div>
				<div>
					Next player: {game.nextPlayersNames && game.nextPlayersNames[0]}
				</div>
				<div>
					Last round results:
				</div>
				<div>
					Round: {game.gameInfo.currentRound}
				</div>
				<div>
					My bet:
				</div>
				<div>
					All dices count:
				</div>
				<div>
					My dices:
				</div>

				{game.nextPlayersNames && game.nextPlayersNames[0] === currentUsername && <div>
					Dice number:
					<div>
						<button>+</button>
						{this.diceNumber}
						<button>-</button>
					</div>
					Dice figure:
					<div>
						<button>+</button>
						{this.diceFigure}
						<button>-</button>
					</div>
					<button onClick={this.moveBet}>Bet</button>
					<button onClick={this.moveNotBelieve}>Not Believe</button>
				</div>}
			</div>
		);
	}
};

// src/app/perudo/perudo.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

import { GamesserverService } from './../gamesserver.service';

@Component({
  selector: 'app-perudo',
  templateUrl: './perudo.component.html',
  styleUrls: ['./perudo.component.css']
})
export class PerudoComponent implements OnInit, OnDestroy {
  gameSubscription: any;
  game: any = { gameInfo: {} };
  currentUsernameSubscription: any;
  currentUsername: any;
  diceNumber: number;
  diceFigure: number;
  allDicesCount: number;

  currentBet: String = '';
  myBet: String = '';

  myBetNumberIncDisable: Boolean;
  myBetNumberDecDisable: Boolean;
  myBetFigureIncDisable: Boolean;
  myBetFigureDecDisable: Boolean;

  DICES: Array<String>;

  constructor(
    public gamesServer: GamesserverService,
  ) {
    this.DICES = gamesServer.DICES;

    this.gameSubscription = gamesServer.getGame()
      .subscribe((openGame) => {
        if (openGame) {
          this.game = openGame;
          this.updateAllDicesCount();
          this.updateCurrentBet();
          this.updateMyBet();
        }
      });

    this.currentUsernameSubscription = gamesServer.getCurrentUsername()
      .subscribe((currentUsername) => {
        this.currentUsername = currentUsername;
        this.updateMyBet();
      });
  }

  updateAllDicesCount() {
    if (this.game.gameInfo.players) {
      this.allDicesCount = 0;
      for (let i = 0; i < this.game.gameInfo.players.length; i++) {
        this.allDicesCount += this.game.gameInfo.players[i].dicesCount;
      }
    }
  }

  updateCurrentBet() {
    this.currentBet = '';
    for (let i = 0; i < this.game.gameInfo.currentDiceNumber; i++) {
      this.currentBet = `${this.currentBet}${this.DICES[this.game.gameInfo.currentDiceFigure - 1]}`;
    }
  }

  updateMyBet() {
    if (this.game.nextPlayersNames
      && this.game.nextPlayersNames.indexOf(this.currentUsername) >= 0) {
      if (!this.diceNumber || !this.diceFigure) {
        this.diceNumber = 1;
        this.diceFigure = 2;
        if (this.game.gameInfo.currentDiceNumber && this.game.gameInfo.currentDiceFigure) {
          this.diceNumber = this.game.gameInfo.currentDiceNumber + 1;
          this.diceFigure = this.game.gameInfo.currentDiceFigure;
        }
      }
    }

    this.myBet = '';
    for (let i = 0; i < this.diceNumber; i++) {
      this.myBet = `${this.myBet}${this.DICES[this.diceFigure - 1]}`;
    }

    this.myBetNumberIncDisable = this.diceNumber >= this.allDicesCount;
    this.myBetNumberDecDisable = this.diceNumber <= 1
      || this.diceNumber <= this.game.gameInfo.currentDiceNumber
      || (this.diceNumber <= this.game.gameInfo.currentDiceNumber + 1 && this.diceFigure <= this.game.gameInfo.currentDiceFigure);

    this.myBetFigureIncDisable = this.diceFigure >= 6;
    this.myBetFigureDecDisable = this.diceFigure <= 2
      || (this.diceNumber === this.game.gameInfo.currentDiceNumber && this.diceFigure <= this.game.gameInfo.currentDiceFigure + 1);
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    this.gameSubscription.unsubscribe();
    this.currentUsernameSubscription.unsubscribe();
  }

  diceNumberInc() {
    if (!this.myBetNumberIncDisable) {
      this.diceNumber++;
      this.updateMyBet();
    }
  }

  diceNumberDec() {
    if (!this.myBetNumberDecDisable) {
      this.diceNumber--;
      this.updateMyBet();
    }
  }

  diceFigureInc() {
    if (!this.myBetFigureIncDisable) {
      this.diceFigure++;
      this.updateMyBet();
    }
  }

  diceFigureDec() {
    if (!this.myBetFigureDecDisable) {
      this.diceFigure--;
      this.updateMyBet();
    }
  }

  moveBet() {
    this.gamesServer.move({ number: this.diceNumber, figure: this.diceFigure });
    this.diceNumber = 0;
    this.diceFigure = 0;
  }

  moveNotBelieve() {
    this.gamesServer.move({ notBelieve: true });
    this.diceNumber = 0;
    this.diceFigure = 0;
  }
}

<span class="label">Next player:</span> {{ game.nextPlayersNames }}
<br>
<div *ngIf="currentBet">
  <span class="label">Last player:</span>
  {{ game.players[game.gameInfo.lastPlayerNumber] && game.players[game.gameInfo.lastPlayerNumber].username }}
  <br>
  <br>
</div>

<span class="label">Last round results:</span> {{ '' }}
<div *ngFor="let player of game.gameInfo.players; let i = index">
  &nbsp;&nbsp;&nbsp;
  <span class="label">{{ game.players[i].username }}</span>'s dices:
  <span class="bet" *ngFor="let dice of game.gameInfo.lastRoundResults[i]"> {{ DICES[dice - 1] }}</span>
</div>
<span class="label">Round:</span> {{ game.gameInfo.currentRound }}

<br>
<br>
<div *ngIf="currentBet">
  <span class="label">Current bet:</span>
  <div class="bet">{{ currentBet }}</div>
</div>
<div *ngIf="game.nextPlayersNames && game.nextPlayersNames.indexOf(currentUsername) >= 0">
  <span class="label">My bet:</span>
  <div class="bet">{{ myBet }}</div>
</div>
<br>

<span class="label">All dices count:</span> {{ allDicesCount }}
<div *ngFor="let player of game.gameInfo.players; let i = index">
  <div *ngIf="game.players[i].username !== currentUsername">
    <span class="label">{{ game.players[i].username }}</span>'s dices count: {{ game.gameInfo.players[i].dicesCount }}
  </div>
</div>

<div *ngFor="let player of game.gameInfo.players; let i = index">
  <div *ngIf="game.players[i].username === currentUsername">
    <span class="label">My dices:</span>
    <span class="bet" *ngFor="let dice of game.gameInfo.players[i].dices"> {{ DICES[dice - 1] }}</span>
  </div>
</div>
<br>

<div *ngIf="game.nextPlayersNames && game.nextPlayersNames.indexOf(currentUsername) >= 0">
  <p>Dice number</p>
  <p>
    <button mat-raised-button (click)="diceNumberDec()" [disabled]="myBetNumberDecDisable">-</button>
    {{ diceNumber }}
    <button mat-raised-button (click)="diceNumberInc();" [disabled]="myBetNumberIncDisable">+</button>
  </p>

  <p>Dice figure</p>
  <p>
    <button mat-raised-button (click)="diceFigureDec();" [disabled]="myBetFigureDecDisable">-</button>
    {{ diceFigure }}
    <button mat-raised-button (click)="diceFigureInc();" [disabled]="myBetFigureIncDisable">+</button>
  </p>

  <button mat-raised-button (click)="moveBet()">Bet</button>&nbsp;
  <button mat-raised-button (click)="moveNotBelieve()" [disabled]="!currentBet">Not Believe</button>
</div>
