// src/containers/no-thanks/index.tsx
import * as React from 'react';
import { Button } from '@material-ui/core';

import { CHIP } from '../../services';
import * as types from '../../constants';

interface NoThanksProps extends React.Props<{}> {
	game: types.Game,
	currentUsername: string | '',
	move: any,
}

export class NoThanks extends React.Component<NoThanksProps, {}> {
	render() {
		const {
			game: {
				gameData,
				name,
				nextPlayersNames,
				players,
			},
			currentUsername,
			move,
		} = this.props;

		const { currentCard, currentCardCost, cardsLeft } = JSON.parse(gameData);

		const myTurn = nextPlayersNames && nextPlayersNames.indexOf(currentUsername) >= 0;

		// let myChips = 0;
		players.forEach((player, index) => {
			if (player.username === currentUsername) {
				// myChips = playersInGame[index] && playersInGame[index].chips || 0;
			}
		});

		return (
			<div>
				<div>
					{name}
				</div>
				<div>
					{myTurn && <span>YOUR MOVE!</span>}
				</div>
				<div>
					Next player: {nextPlayersNames && nextPlayersNames[0]}
				</div>
				<div>
					Cards left: {cardsLeft}
				</div>
				<div>
					Current card: {currentCard}
				</div>
				<div>
					{Array((currentCardCost || 0) + 1).join(CHIP)} ({currentCardCost})
				</div>

				{/* {playersInGame.map((playerInGame, index) => (
					<div key={index}>
						{players[index].username !== currentUsername && <div key={index}>
							{players[index].username}:
							{(playerInGame.cards || []).map((card, i) => (
								<span key={i}>
									{card},
								</span>
							))}
						</div>}
					</div>
				))}

				{playersInGame.map((playerInGame, index) => (
					<div key={index}>
						{(players[index].username === currentUsername) && <div>
							<div>
								My chips: {Array(myChips + 1).join(CHIP)} ({myChips})
							</div>
							<div>
								My cards:
								{(playerInGame.cards || []).map((card, i) => (
									<span key={i}>
										{card},
									</span>
								))}
							</div>
							<div>
								My points: {playerInGame.points}
							</div>
						</div>}
					</div>
				))} */}

				{myTurn && <div>
					<Button
						variant='contained'
						color='primary'
						onClick={() => { move({ takeCard: false }); }}
						// disabled={!myChips}
					>
						Pay
					</Button>
					<Button variant='contained' color='primary' onClick={() => { move({ takeCard: true }); }}>Take</Button>
				</div>}
			</div>
		);
	}
};

// src/app/no-thanks/no-thanks.component.ts
import { Component, OnInit } from '@angular/core';

import { GamesserverService } from './../gamesserver.service';

@Component({
  selector: 'app-no-thanks',
  templateUrl: './no-thanks.component.html',
  styleUrls: ['./no-thanks.component.css']
})
export class NoThanksComponent implements OnInit {
  gameSubscription: any;
  game: any = { gameInfo: {} };
  currentUsernameSubscription: any;
  currentUsername: any;

  constructor(
    public gamesServer: GamesserverService,
  ) {
    this.gameSubscription = gamesServer.getGame().subscribe((openGame) => {
      if (openGame) {
        this.game = openGame;
      }
    });
    this.currentUsernameSubscription = gamesServer.getCurrentUsername().subscribe((currentUsername) => {
      console.log('app-no-thanks: currentUsername', currentUsername);
      this.currentUsername = currentUsername;
    });
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    this.gameSubscription.unsubscribe();
    this.currentUsernameSubscription.unsubscribe();
  }

  movePay() {
    this.gamesServer.move({ takeCard: false });
  }

  moveTake() {
    this.gamesServer.move({ takeCard: true });
  }
  
}

<span class="label">Next player:</span> {{ game.nextPlayersNames }}
<br>
<span class="label">Cards left:</span> {{ game.gameInfo.cardsLeft }}
<br>
<br>
<span class="label">Current card:</span>
<br>
<div>
  <span class="nothanks-bold">{{ game.gameInfo.currentCard }}</span>
</div>
<span class="chips">{{ CHIP.repeat(game.gameInfo.currentCardCost) }}</span> ({{ game.gameInfo.currentCardCost }})
<br>
<br>

<div *ngFor="let player of game.gameInfo.players; let i = index">
  <div *ngIf="game.players[i].username !== currentUsername">
    <span class="label">{{ game.players[i].username }}</span>'s cards:
    <span *ngFor="let card of player.cards; let i = index">
      <span class="{{ i === 0 || card !== player.cards[i - 1] + 1 ? 'nothanks-bold' : 'nothanks-grey' }}"> {{ card }}</span>
    </span>
  </div>
</div>

<div *ngFor="let player of game.gameInfo.players; let i = index">
  <div *ngIf="game.players[i].username === currentUsername">
    <br>
    <span class="label">My chips: </span>
    <span class="chips">{{ CHIP.repeat(player.chips) }}</span> ({{ player.chips }})
    <br>
    <br>
    <span class="label">My cards: </span>
    <span *ngFor="let card of player.cards; let i = index">
      <span class="{{ i === 0 || card !== player.cards[i - 1] + 1 ? 'nothanks-bold' : 'nothanks-grey' }}"> {{ card }}</span>
    </span>
    <br>
    <br>
    <span class="label">My points: </span>
    <span class="result">{{ player.points }}</span>
  </div>
</div>
<br>

<div *ngIf="game.nextPlayersNames && game.nextPlayersNames.indexOf(currentUsername) >= 0">
  <button mat-raised-button (click)="movePay()">Pay</button>&nbsp;
  <button mat-raised-button (click)="moveTake()">Take</button>
</div>
